# Generated by Django 6.0.1 on 2026-03-04 04:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTrabajo',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'areas_trabajo',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'carreras',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=50)),
                ('nombre_contacto', models.CharField(max_length=150)),
                ('correo_contacto', models.CharField(max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'instituciones',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(max_length=20)),
                ('nacionalidad', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=80)),
                ('telefono_alterno', models.CharField(blank=True, max_length=20, null=True)),
                ('provincia', models.CharField(max_length=100)),
                ('canton', models.CharField(max_length=100)),
                ('foto_url', models.CharField(blank=True, max_length=500, null=True)),
                ('qr_url', models.CharField(blank=True, max_length=500, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('empresa', 'Empresa'), ('aspirante', 'Aspirante')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('consentimiento', models.BooleanField(default=False)),
                ('fecha_consentimiento', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('preferencias', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('nivel_educativo', models.CharField(choices=[('secundaria', 'Secundaria'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('licenciatura', 'Licenciatura'), ('maestria', 'Maestría')], max_length=50)),
                ('estado_laboral', models.CharField(choices=[('buscando', 'Buscando empleo'), ('empleado', 'Empleado'), ('desempleado', 'Desempleado')], max_length=50)),
                ('sobre_mi', models.TextField(blank=True, null=True)),
                ('foto_url', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('habilidades_tecnicas', models.JSONField(blank=True, default=list, null=True)),
                ('habilidades_blandas', models.JSONField(blank=True, default=list, null=True)),
                ('experiencia', models.JSONField(blank=True, default=list, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('carrera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.carrera')),
                ('institucion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.institucion')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'aspirantes',
            },
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('predeterminado', models.BooleanField(default=False)),
                ('archivo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('extraido_por_ia', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aspirante')),
            ],
            options={
                'db_table': 'curriculos',
            },
        ),
        migrations.CreateModel(
            name='Practicante',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(max_length=200)),
                ('nivel_academico', models.CharField(max_length=50)),
                ('periodo_practica', models.CharField(max_length=100)),
                ('horas_requeridas', models.SmallIntegerField()),
                ('estado_pasantia', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aspirante')),
                ('carrera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.carrera')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.institucion')),
            ],
            options={
                'db_table': 'practicantes',
            },
        ),
        migrations.CreateModel(
            name='ProgramaFormacion',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_programa', models.CharField(max_length=100)),
                ('duracion_meses', models.SmallIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carrera')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.institucion')),
            ],
            options={
                'db_table': 'programas_formacion',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=80)),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('canal', models.CharField(max_length=50)),
                ('leido', models.BooleanField(default=False)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
        migrations.AddField(
            model_name='institucion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('datos_globales', models.TextField(blank=True, null=True)),
                ('servicios_cr', models.TextField(blank=True, null=True)),
                ('nombre_contacto', models.CharField(max_length=150)),
                ('correo_contacto', models.CharField(max_length=255)),
                ('url_externa', models.CharField(blank=True, max_length=500, null=True)),
                ('gestiona_en_plataforma', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('tipo_entidad', models.CharField(max_length=80)),
                ('entidad_id', models.CharField(max_length=36)),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('ip_direccion', models.CharField(max_length=45)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'auditoria',
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel_educativo', models.CharField(max_length=50)),
                ('tipo_vacante', models.CharField(max_length=50)),
                ('url_externa', models.CharField(blank=True, max_length=500, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area_trabajo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.areatrabajo')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.institucion')),
            ],
            options={
                'db_table': 'vacantes',
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
                ('visto', models.BooleanField(default=False)),
                ('contratado', models.BooleanField(default=False)),
                ('puntaje_ia', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('postulado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aspirante')),
                ('curriculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.curriculo')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vacante')),
            ],
            options={
                'db_table': 'postulaciones',
            },
        ),
    ]
