# Generated by Django 6.0.3 on 2026-03-03 20:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='institucion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.institucion'),
        ),
        migrations.AddField(
            model_name='vacante',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.institucion'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.empresa'),
        ),
        migrations.CreateModel(
            name='ProgramaFormacion',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_programa', models.CharField(max_length=100)),
                ('duracion_meses', models.SmallIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carrera')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.institucion')),
            ],
            options={
                'db_table': 'programas_formacion',
            },
        ),
    ]
