# Generated by Django 6.0.1 on 2026-03-04 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aspirante_empresa_recomendada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('empresa', 'Empresa'), ('aspirante', 'Aspirante'), ('institucion', 'Institución')], max_length=20),
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modalidad', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=100)),
                ('imagen_url', models.CharField(blank=True, max_length=500, null=True)),
                ('url_inscripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.institucion')),
            ],
            options={
                'db_table': 'capacitaciones',
            },
        ),
    ]
