# Generated by Django 6.0.2 on 2026-03-02 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_persona_usuario_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='estado_laboral',
            field=models.CharField(choices=[('buscando', 'Buscando empleo'), ('empleado', 'Empleado'), ('desempleado', 'Desempleado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='nivel_educativo',
            field=models.CharField(choices=[('secundaria', 'Secundaria'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('licenciatura', 'Licenciatura'), ('maestria', 'Maestría')], max_length=50),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.persona'),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
