# Generated by Django 6.0.1 on 2026-03-04 13:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuario_rol_capacitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aspirante')),
                ('capacitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.capacitacion')),
                ('vacante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vacante')),
            ],
            options={
                'db_table': 'favoritos',
                'unique_together': {('aspirante', 'capacitacion'), ('aspirante', 'vacante')},
            },
        ),
        migrations.CreateModel(
            name='InscripcionCapacitacion',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aspirante')),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.capacitacion')),
            ],
            options={
                'db_table': 'inscripciones_capacitacion',
                'unique_together': {('aspirante', 'capacitacion')},
            },
        ),
    ]
