# Generated by Django 6.0.2 on 2026-03-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_aspirante_estado_laboral_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='area',
        ),
    ]
