# Generated by Django 6.0.1 on 2026-03-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_favorito_inscripcioncapacitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sector',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tamano_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
