# Generated by Django 6.0.1 on 2026-03-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_carrera_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='habilidades_blandas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='habilidades_tecnicas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
