# Generated by Django 6.0.1 on 2026-03-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_aspirante_habilidades_blandas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
