# Generated by Django 6.0.1 on 2026-03-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_entrevistas_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password_plano',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
