# Generated by Django 6.0.1 on 2026-03-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_aspirante_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='experiencia',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
