# Generated by Django 6.0.1 on 2026-03-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_aspirante_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='foto_url',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
