# Generated by Django 6.0.1 on 2026-03-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_usuario_password_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
