# Generated by Django 6.0 on 2026-03-03 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aspirante_institucion_origen_vacante_institucion_and_more'),
        ('api', '0009_usuario_preferencias'),
    ]

    operations = [
    ]
